FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.11

RUN apk add influxdb

RUN sed -i 's|/var/lib/influxdb|/data/influxdb|g' /etc/influxdb.conf
RUN mkdir /etc/influxdb
RUN cp /etc/influxdb.conf /etc/influxdb/

#Build library directory. This is where data is stored.

# RUN mkdir -p /var/lib/influxdb
# RUN chown influxdb:influxdb /var/lib/influxdb

CMD ["influxd"]
